baseURL = "/"
languageCode = "en-us"
title = "GenTest"
description = "Capstone Team 22: GenTest"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "Team Website for GenTest Capstone Team"
    logo = "logo.jpg"
    twitterAuthor = "@natedayta"
    githubUsername = "nathancday"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Team"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Documents"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Schedule"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
#
#[[menu.icon]]
#    url = "mailto:nathancday@gmail.com"
#    name = "far fa-envelope"
#    weight = 1
#
#[[menu.icon]]
#    url = "https://github.com/NathanCDay"
#    name = "fab fa-github"
#    weight = 2
#
#[[menu.icon]]
#    url = "https://twitter.com/natedayta/"
#    name = "fab fa-twitter"
#    weight = 3
#
#[[menu.icon]]
#    url = "https://www.linkedin.com/in/nathan-day-59b48435/"
#    name = "fab fa-linkedin"
#    weight = 4
#
#[[menu.icon]]
#    url = "https://www.stackoverflow.com/users/5878751/nate"
#    name = "fab fa-stack-overflow"
#    weight = 5
